blog/templates/blog/ProFive/ProFive/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from test_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^$',views.index,name='index'),
    url('^special/',views.special,name='special'),
    url('^test_app/',include('test_app.urls')),
    url('^logout/$',views.user_logout,name='logout'),
]

blog/templates/blog/ProFive/test_app/urls.py
from django.conf.urls import url
from test_app import views

app_name = 'test_app'

urlpatterns = [
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
    url(r'^$',views.PostListView.as_view(),name='post_list'),
    url(r'^about/$',views.AboutView.as_view(),name='about'),
    url(r'^post/(?P<pk>\d+)$',views.PostDetailView.as_view(),name='post_detail'),
    url(r'^post/new/$',views.CreatePostView.as_view(),name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$',views.UpdatePostView.as_view(),name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$',views.DeletePostView.as_view(),name='post_remove'),
    url(r'^drafts/$',views.DraftListView.as_view(),name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/comment/$',views.add_comment_to_post,name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$',views.comment_approve,name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$',views.comment_remove,name='comment_remove'),
    url(r'^post/(?P<pk>\d+)/publish/$',views.publish_post,name='post_publish'),
]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog.urls')),
    url(r'accounts/login/$',views.login,name='login'),
    url(r'accounts/logout/$',views.logout, name='logout', kwargs={'next_page': '/'}),
]

blog/templates/blog/ProFive/test_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

blog/templates/blog/ProFive/test_app/forms.py
from django import forms
from django.contrib.auth.models import User
from test_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

blog/templates/blog/ProFive/test_app/views.py
from django.shortcuts import render
from test_app.forms import UserForm, UserProfileInfoForm

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request,'test_app/index.html')

def register(request):

    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save() # Save userform to db
            user.set_password(user.password) # Hashing password
            user.save() #Update with hashed password

            profile = profile_form.save(commit=False)
            # Set one to one relationship bw profile and user
            profile.user = user

            # Check if profile picture is provided
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'test_app/registration.html',
                        {'user_form':user_form,
                        'profile_form':profile_form,
                        'registered':registered})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You're logged in")

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        #django default authentication
        user = authenticate(username=username, password=password)

        # authentication success
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Inactive account. Contact the administrator")

        else:
            print("Login error. Username: {}, Password: {}".format(username,password))
            return HttpResponse("Username and/or password invalid")

    else:
        return render(request, 'test_app/login.html', {})

blog/templates/blog/ProFive/templates/test_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class='nav navbar-nav'>
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'admin:index' %}">Admin</a></li>
          <li><a href="{% url 'test_app:register' %}">Register</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a href="{% url 'test_app:user_login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      <!-- Everything goes here -->
      {% endblock %}
    </div>
  </body>
</html>

blog/templates/blog/ProFive/templates/test_app/index.html
{% extends 'test_app/base.html' %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>This is the index page</h1>
    {% if user.is_authenticated %}
      <h2>Welcome {{ user.username }}</h2>
    {% else %}
      <h2>Welcome. Please log in to continue</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

blog/templates/blog/ProFive/templates/test_app/login.html
<!DOCTYPE html>
{% extends 'test_app/base.html' %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Welcome to login page</h1>
    <form action="{% url 'test_app:user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="username">

      <label for="password">Password:</label>
      <input type="password" name="password">

      <input type="submit" name="" value="Login">

    </form>

  </div>

</div>
{% endblock %}

blog/templates/blog/ProFive/templates/test_app/registration.html
<!DOCTYPE html>
{% extends 'test_app/base.html' %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank you for registering</h1>
    {% else %}
      <h1>Welcome to registration page</h1>
      <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p}}
        <input type="submit" name="" value="Register">
      </form>
    {% endif %}
  </div>

</div>
{% endblock %}